import BottomNavBar from "@/components/BottomNavBar";
import ConnectWithCyberConnect from "@/components/ConnectWithCyberConnect";
import Header from "@/components/Header";
import MainContent from "@/components/MainContent";
import Sidebar from "@/components/Sidebar";
import Head from "next/head";
import React from "react";

type Props = {};

const Create = (props: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={""}>
        <Header />
        <div className="flex">
          <Sidebar />

          <div className="w-full flex min-h-full  px-0 md:px-20 flex-1 md:w-400px">
            <div className=" w-full   px-2 md:px-0 pb-12">
              <div className="py-4 md:flex items-center justify-end hidden ">
                <ConnectWithCyberConnect />
              </div>

              <form>
                <input type="file" name="" id="" />
              </form>
            </div>
          </div>
        </div>

        <BottomNavBar />
      </main>
    </>
  );
};

export default Create;
