import BottomNavBar from "@/components/BottomNavBar";
import ConnectWithCyberConnect from "@/components/ConnectWithCyberConnect";
import Header from "@/components/Header";
import { CommentIcon, LikeIcon, SaveIcon, SendIcon } from "@/components/ImportantIcons";
import Sidebar from "@/components/Sidebar";
import useLike from "@/hooks/useLike";
import { MediaRenderer } from "@thirdweb-dev/react";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { FC, ReactElement,useState } from "react";
import { AiFillHeart } from "react-icons/ai";

type Props = {};

const Comment: FC<Props> = (props): ReactElement => {
  const router = useRouter();
  const [open, setOpen] = useState<boolean>(false);
  const { contentID,image } = router.query;
  const [loading, setLoading] = useState<boolean>(false);
  const [liked, setLiked] = useState<boolean>();

  const {like} = useLike();

  if(!contentID && !image){
    return <div className="w-full min-h-[300px] flex items-center justify-center">
      <div className="w-8 h-8 border-4 border-b-transparent rounded-full animate-spin"></div>
    </div>
  }

  return(
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={""}>
        <Header />
        <div className="flex">
          <Sidebar />
          <div className="w-full flex min-h-full  px-0 md:px-20 flex-1">
            <div className=" w-full px-2 md:px-0 pb-12">
              <div className="py-4 md:flex items-center justify-end hidden ">
                <ConnectWithCyberConnect setOpen={setOpen} />
              </div>

              <div className="h-fit py-2 flex flex-col gap-4 max-w-[500px] pt-4 pb-8">
                <div className="relative w-full h-[400px]">
                  <MediaRenderer src={image as string} alt="comment_image" width="100%" height="100%" style={{objectFit:"contain"}} />
                </div>

                <div className="mt-[4px]">
        {/* important options */}
        <div className="flex items-center justify-between pb-[6px]">
          <div className="flex gap-4">
            {liked ? (
              <span className="py-2 text-instaRed cursor-pointer text-2xl">
                <AiFillHeart />
              </span>
            ) : (
              <span
                className="py-2 cursor-pointer"
                onClick={async () => {
                  if (loading) return;
                  setLoading(true);
                  let result = await like(
                    contentID as string
                  );
                  if (result) {
                    setLiked(true);
                  }

                  setLoading(false);
                }}
              >
                <LikeIcon />
              </span>
            )}
            <span className="py-2 cursor-pointer">

                <CommentIcon />

            </span>
            <span className="py-2 cursor-pointer">
              <SendIcon />
            </span>
          </div>
          <span className="py-2">
            <SaveIcon />
          </span>
        </div>
      </div>
              </div>

            </div>
          </div>
        </div>
        <BottomNavBar />
      </main>
    </>
  );
};

export default Comment;
